### ISSUE TITLE
Suggestion 

### ISSUE THREAD

**Issue by Willtom999** [Aetheam/MaintenanceSystem#1]
Mettre une permission et si la personne a cette permission elle ne sera pas kick

**Comment by achedon12** [comment]
Totalement débile parce que justement le but d'une maintenance c'est que tout le monde soit kick du serveur. Mais après il est vrai que, rajouter une option ou seulement les personnes n'ayant pas une permission serait envisageable

**Comment by royaljacques** [comment]
je vais de toute magnière faire un system d'option avec le form ou il pourrons séléctioner ce que il veulent faire .
